version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: SpaceReservation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrongPassword123!
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
